spring.datasource.url=jdbc:postgresql://ep-long-brook-acao1l0l-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_3YdEBqM9NbzC
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false